export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADD_DIKIDI_ACCOUNT = 'ADD_DIKIDI_ACCOUNT';
export const FETCH_DIKIDI_ACCOUNT = 'FETCH_DIKIDI_ACCOUNT';
export const FETCH_DIKIDI_STUDIOS = 'FETCH_DIKIDI_STUDIOS';